/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//#include <stdint.h>
#include "stm32f4xx.h"
#include "stm32f4xx_ll_bus.h"
#include "stm32f4xx_ll_gpio.h"
#include "stm32f4xx_ll_system.h"
#include "stm32f4xx_ll_tim.h"
#include "stm32f4xx_ll_usart.h"
#include "stm32f4xx_ll_adc.h"
#include "stm32f4xx_ll_exti.h"
#include "stm32f4xx_ll_iwdg.h"
#include "stm32f4xx_ll_dma.h"
#include <stdio.h>

#define ADC_BUFFER_SIZE 20

volatile uint8_t ButtonC=1;
volatile uint32_t last_interrupt_time=0;
volatile uint32_t timer_adc_trigger = 0;
volatile uint8_t Loop=0;
uint16_t adc_data[ADC_BUFFER_SIZE];
int wynik = 0;

void USART2_IRQHandler()
{
	if (LL_USART_IsActiveFlag_RXNE(USART2))
	{
		uint8_t receivedData = LL_USART_ReceiveData8(USART2);
		if(receivedData>='a' && receivedData<='z')
		{
			receivedData -=32;
		}

		LL_USART_TransmitData8(USART2, receivedData);
		LL_TIM_GetCounter(TIM2);
	}


}

void EXTI15_10_IRQHandler(void)
{
    if (LL_EXTI_IsActiveFlag_0_31(LL_EXTI_LINE_13) != RESET)
    {

        LL_EXTI_ClearFlag_0_31(LL_EXTI_LINE_13);

        if(LL_TIM_IsActiveFlag_UPDATE(TIM3))
        {
        	LL_TIM_ClearFlag_UPDATE(TIM3);
            if(LL_GPIO_IsInputPinSet(GPIOC, LL_GPIO_PIN_13) == 0)
            {

                if(ButtonC == 1)
                {
                    LL_TIM_SetPrescaler(TIM2, 31);
                    ButtonC = 0;
                }
                else
                {
                    LL_TIM_SetPrescaler(TIM2, 159);
                    ButtonC = 1;
                }
            }

            Loop=1;

        }
    }
}

int main(void)
{
	int CompareValue=0;
	uint8_t counter=0;
	uint8_t up=1;


	//Dioda led
	LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOA);				//Uruchomienie AHB1 dla GPIOA
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_5, LL_GPIO_MODE_OUTPUT);		//Ustawienie pinu na output
	LL_GPIO_SetOutputPin(GPIOA, LL_GPIO_PIN_5);							//Ustawienie pinu na 1

	//Timer
	LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_TIM2);					//Uruchomienie APB1 dla TIM2
	LL_TIM_SetPrescaler(TIM2, 159);										//Ustawienie częstotliwości
	LL_TIM_SetAutoReload(TIM2, 999);									//Ustawienie do ilu ma liczyć
	LL_TIM_EnableCounter(TIM2);											//Uruchomienie timera

	LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_TIM3);
	LL_TIM_SetPrescaler(TIM3, 1599);
	LL_TIM_SetAutoReload(TIM3, 2000);
	LL_TIM_EnableCounter(TIM3);

	//Button
	LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOC);				//Uruchomienie AHB1 dla GPIOC
	LL_GPIO_SetPinMode(GPIOC, LL_GPIO_PIN_13, LL_GPIO_MODE_INPUT);		//Ustawienie pinu na input
	LL_GPIO_SetPinPull(GPIOC, LL_GPIO_PIN_13, LL_GPIO_PULL_UP);			//Ustawienie PUUL UP

	//PRZERWANIA
	LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_SYSCFG); // Zegar dla SYSCFG
	LL_SYSCFG_SetEXTISource(LL_SYSCFG_EXTI_PORTC, LL_SYSCFG_EXTI_LINE13); // PC13 -> EXTI13
	LL_EXTI_EnableIT_0_31(LL_EXTI_LINE_13); // Włącz linię
	LL_EXTI_EnableFallingTrig_0_31(LL_EXTI_LINE_13); // Zbocze opadające
	//Przerwanie Button
	NVIC_SetPriority(EXTI15_10_IRQn,1);
	NVIC_EnableIRQ(EXTI15_10_IRQn);


	//Usart
	LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_USART2);				//Uruchomienie APB1 dla UART2
	LL_USART_Enable(USART2);											//Uruchomienie Usart2
	LL_USART_SetTransferDirection(USART2, LL_USART_DIRECTION_TX_RX);	//Ustawisz wysyłanie danych przez TX RX
	LL_USART_SetBaudRate(USART2, 16000000, 16, 115200);					//Ustawienie dla USAR2,(16000000-Przekazanie szybkości zegara),16-OverSampling,a 115200-Baud szybkość transmisji danych

	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_2, LL_GPIO_MODE_ALTERNATE);	//Ustawienie pinu na alternatywne działanie
	LL_GPIO_SetAFPin_0_7(GPIOA, LL_GPIO_PIN_2, LL_GPIO_AF_7);			//Ustawienie alternatywnej funkcji na AF7 (AF7-Usart2_TX)
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_3, LL_GPIO_MODE_ALTERNATE);	//Ustawienie pinu na alternatywne działanie
	LL_GPIO_SetAFPin_0_7(GPIOA, LL_GPIO_PIN_3, LL_GPIO_AF_7);			//Ustawienie alternatywnej funkcji na AF7 (AF7-Usart2_RX)

	//PWM
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_1, LL_GPIO_MODE_ALTERNATE);
	LL_GPIO_SetAFPin_0_7(GPIOA, LL_GPIO_PIN_1, LL_GPIO_AF_1);
	LL_TIM_OC_SetMode(TIM2, LL_TIM_CHANNEL_CH2, LL_TIM_OCMODE_PWM1);
	LL_TIM_CC_EnableChannel(TIM2, LL_TIM_CHANNEL_CH2);
	LL_TIM_OC_SetCompareCH2(TIM2, CompareValue);


	//Usart Przerwania
	NVIC_SetPriority(USART2_IRQn,0);		//Ustawienie priorytetu przerwania	(0-Najwyższy priorytet)
	NVIC_EnableIRQ(USART2_IRQn);			//Uruchomienie przerwań dla USAR2
	LL_USART_EnableIT_RXNE(USART2);			//Generowanie przerwania gdy odbierze dane

	//ADC
	LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_ADC1);					//Uruchomienie APB2 dla ADC1
	LL_GPIO_SetPinMode(GPIOA, LL_GPIO_PIN_0, LL_GPIO_MODE_ANALOG);		//Ustawienie pinu na Analog
	LL_GPIO_SetPinPull(GPIOA, LL_GPIO_PIN_0, LL_GPIO_PULL_NO);   		 // Wyłącza rezystory podciągające
	LL_ADC_SetCommonClock(__LL_ADC_COMMON_INSTANCE(ADC1), LL_ADC_PATH_INTERNAL_NONE);
	LL_ADC_SetResolution(ADC1, LL_ADC_RESOLUTION_12B);					//Rozdzielczosc 12-Bitow(wynik 0-4095)
	LL_ADC_SetDataAlignment(ADC1, LL_ADC_DATA_ALIGN_RIGHT);				// Dosuń wynik do prawej strony 16-bitowej zmiennej
	LL_ADC_SetSequencersScanMode(ADC1, LL_ADC_SEQ_SCAN_DISABLE);		// Nie skanuj wielu kanałów naraz
	LL_ADC_REG_SetSequencerRanks(ADC1, LL_ADC_REG_RANK_1, LL_ADC_CHANNEL_0);	// PA0 to Kanał 0
	LL_ADC_SetChannelSamplingTime(ADC1, LL_ADC_CHANNEL_0, LL_ADC_SAMPLINGTIME_480CYCLES);
	LL_ADC_Enable(ADC1);
	LL_ADC_REG_SetDMATransfer(ADC1, LL_ADC_REG_DMA_TRANSFER_UNLIMITED);


	//WatchDogs IWDG
	LL_IWDG_Enable(IWDG);									// Uruchomienie IWDG (to automatycznie włącza też zegar LSI)
	LL_IWDG_EnableWriteAccess(IWDG);						// Odblokowanie dostępu do rejestrów (IWDG jest domyślnie chroniony przed zapisem)
	LL_IWDG_SetPrescaler(IWDG, LL_IWDG_PRESCALER_32);		//  Ustawienie dzielnika (Prescaler)
	LL_IWDG_SetReloadCounter(IWDG, 4095); 					//  Ustawienie wartości, od której pies odlicza w dół (Reload)
	while(LL_IWDG_IsReady(IWDG) != 1);						//  Czekanie, aż parametry zostaną zapisane w pamięci IWDG
	LL_IWDG_ReloadCounter(IWDG);							//  "Nakarmienie psa" po raz pierwszy (odświeżenie licznika)


	//DMA
	LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_DMA2);
	LL_DMA_ConfigTransfer(DMA2, LL_DMA_STREAM_0,
	                      LL_DMA_DIRECTION_PERIPH_TO_MEMORY | // Kierunek: z ADC do RAM
	                      LL_DMA_PRIORITY_HIGH              | // Priorytet
	                      LL_DMA_MODE_CIRCULAR              | // Tryb kołowy - mierzy w kółko bez przerwy
	                      LL_DMA_PERIPH_NOINCREMENT         | // Adres ADC stoi w miejscu
	                      LL_DMA_MEMORY_INCREMENT           | // Adres w RAM przesuwa się do przodu
	                      LL_DMA_PDATAALIGN_HALFWORD        | // Dane 16-bitowe (ADC ma 12)
	                      LL_DMA_MDATAALIGN_HALFWORD);        // Pamięć też 16-bitowa


	LL_DMA_SetChannelSelection(DMA2, LL_DMA_STREAM_0, LL_DMA_CHANNEL_0);		//Wybór kanału

	LL_DMA_ConfigAddresses(DMA2, LL_DMA_STREAM_0,
	                       LL_ADC_DMA_GetRegAddr(ADC1, LL_ADC_DMA_REG_REGULAR_DATA), // Zródło: rejestr DR przetwornika
	                       (uint32_t)&adc_data,                                     // Cel: nasza tablica
	                       LL_DMA_DIRECTION_PERIPH_TO_MEMORY);

	LL_DMA_SetDataLength(DMA2, LL_DMA_STREAM_0, ADC_BUFFER_SIZE);
	LL_DMA_EnableStream(DMA2, LL_DMA_STREAM_0);


	//Start pomiarów z ac przez DMA
	LL_ADC_REG_SetContinuousMode(ADC1, LL_ADC_REG_CONV_CONTINUOUS);					 // ADC mierzy jeden raz za drugim
	LL_ADC_REG_StartConversionSWStart(ADC1);										 // Odpalamy pierwszy pomiar - reszta pójdzie "sama"

   while(1)
   {



			 //  LL_USART_TransmitData8(USART2, msg);						//Wysyłanie danych przez USART2

			   if(LL_TIM_IsActiveFlag_UPDATE(TIM2))							//Sprawdzenie czy Flaga dla tim2 jest aktywna czyli czy licznik doliczył do określonej wartości LL_TIM_SetAutoReload
			       {
				   	   //timer_adc_trigger++;
			           LL_TIM_ClearFlag_UPDATE(TIM2);												//Zerowanie Flagi

			           if(up == 1) {
			               CompareValue++;
			               if(CompareValue >= 999) up = 0;
			           } else {
			               CompareValue--;
			               if(CompareValue <= 0) up = 1;
			           }


			           LL_TIM_OC_SetCompareCH2(TIM2, CompareValue);
			           counter++;
			           if(counter==100)
			           {
			        	   LL_GPIO_TogglePin(GPIOA, LL_GPIO_PIN_5);
			        	   counter=0;

			           }

			       }

			/*   if (timer_adc_trigger >= 100) {
			       LL_ADC_REG_StartConversionSWStart(ADC1);
			       timer_adc_trigger = 0;
			   }*/

			   if(LL_DMA_IsActiveFlag_TC0(DMA2)){
				   wynik = 0;
				   LL_DMA_ClearFlag_TC0(DMA2);
				   for(int i=0; i<20; i++)
				   {
					   wynik= wynik + adc_data[i];
				   }
			       wynik=wynik/20;

			       char buffer[60];
			       int len = sprintf(buffer, "Wartosc: %d\r\n", wynik);

			       for (int i = 0; i < len; i++)
			       {
			           while (!LL_USART_IsActiveFlag_TXE(USART2));
			           LL_USART_TransmitData8(USART2, buffer[i]);
			       }
			   }

			   while(Loop==1);

			   LL_IWDG_ReloadCounter(IWDG);

	   }



   }

